version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mock
    versions:
    - 4.0.3
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: aniso8601
    versions:
    - 8.1.1
  - dependency-name: elasticsearch
    versions:
    - 7.10.1
  - dependency-name: flake8
    versions:
    - 3.8.4
  - dependency-name: flake8-tidy-imports
    versions:
    - 4.2.1
