language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make test
deploy:
  provider: pypi
  user: amundsen-dev
  password:
    secure: "NaArANrjv2Zrx461KZnEJ3fwCJDj+6kD+B+FDEHGIyvf1jd0HCJgWL1+73mS7t50UImCahQrk3n9SB1j1Nf681ujenEm5aTix7myGZJyPqgOnARYT9lPalLwn+pEt2xvUI2e0zlhc5uTdhv9b95tUZSZaePd5GB+eEvxFxtJL1AjX6xsweaM/qOz9Bmm/vQ36a2Q2U7eZBElQrSI850mJrR83E2RlCM1M7KBiOJ2AGqtjaT60eAqdQHHY3BtBBgxfFdguQhNiM15gxDuKg7u9vJw9a9KVzQS3Iq2alT9y5jyFay+kNH+xHKaOdHvw1mqD5sgHcCz8Skjs11f46boUp6Tdtc9mvQE3iw2VYdltVGBZIuODehI0qNQurwxg9k0fWub0VhoORuFPfP6UBbc1yC2wCF2L5NDU+9/krmEI9pydJgYAWLU3DuyIYENPJzszRKTP31XFngyO3IAyclidcDKTVbD6vhoz50YdGK1Xqr/c/Y2xNx0o6psXB2QdVOlt52fAckwfrM+Msis1u3oKohiVDL6WWTgYeqw07xH2wZKkBD3wvT5Q8ag2chb7JdDsQ/O2Vr03qC53i/wYOhsX+BgIqljDLNyIMntCONUbBGoP9ChygVT4fD9z1vabzZ9q+Uz1o051nST/gblN9qyLY1Z8loRiXXoYCTCmLDdWpE="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/amundsensearchlibrary
